export class postModel{
post_id!:any
slug!:string
post_author!:string;
post_date!:String;
post_date_gmt!:string;
post_content!:string;
post_title!:string;
post_excerpt!:string;
post_status!:string;
comment_status!:string;
ping_status!:string;
post_password!:string;
post_name!:string;
to_ping!:String;
pinged!:String;
post_modified!:string;
post_modified_gmt!:string;
post_content_filtered!:string;
post_parent!:string;
guid!:string;
menu_order!:string;
post_type!:string;
post_mine_type!:string;
comment_count!:string;
flag!:string;
meta_description!:string;
canonical_url!:string;
visibility!:string;
permalink!:string;
addtags!:string;
featured_Image!:string;
excerpt!:string;
media_type!:string;
media_title!:string;
media_url!:string
immidiate_publish:any
post_img:any
post_mime_type:any
category:any
author_name:any
post_visibility:any
post_time:any
}
